### ISSUE TITLE
iOS postMessage from WebView fails

### ISSUE THREAD

**Issue by jimothyhalpert7** [exponent/exponent#33]
Using code from _UIExplorer_ WebView example:  
https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/WebViewExample.js
https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/messagingtest.html

**Works on Android.**
*exp@0.30.1*  

Output in `exp`
```
exp] <START> Processing asset request  asset: ReactABI12_0_0-js-navigation://postMessage  

[exp] Error: 'ReactABI12_0_0-js-navigation://postMessage' could not be found, because 'ReactABI12_0_0-js-navigation:/' is not a subdirectory of any of the roots  ('/home/jim/exp-init')
    at Promise.all.then.stats (/home/jim/exp-init/node_modules/react-native/packager/react-packager/src/AssetServer/index.js:191:13)
    at tryCallOne (/home/jim/exp-init/node_modules/promise/lib/core.js:37:12)
    at /home/jim/exp-init/node_modules/promise/lib/core.js:123:15
    at flush (/home/jim/exp-init/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

[exp] <END>   Processing asset request  asset: ReactABI12_0_0-js-navigation://postMessage   (6ms)
```

The WebView displayes the text
>**Asset not found**

If we use the html from inside the component, we get the following error
```
[exp] Encountered an error loading page {"domain":"WebKitErrorDomain","canGoBack":false,"target":8,"code":101,"loading":false,"title":"666","canGoForward":false,"description":"The URL can’t be shown","url":"about:blank"}
```

**Comment by terribleben** [comment]
There's a tentative fix here - https://github.com/exponent/exponent/commit/8cd8df903d99ebac1481cd8cce530585b509ed86 shipping at some point this week.

**Comment by jimothyhalpert7** [comment]
Works as of latest version. Thanks a lot!
