### ISSUE TITLE
Cannot find module 'exponent/tools/hashAssetFiles'

### ISSUE THREAD

**Issue by iraycd** [exponent/exponent#72]
Creating an empty project.
While running it, I get.
```
Error: Cannot find module 'exponent/tools/hashAssetFiles'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Bundler._applyAssetPlugins (/Users/iraycd/video/node_modules/react-native/packager/react-packager/src/Bundler/index.js:719:33)
    at _assetServer.getAssetData.then.then.res (/Users/iraycd/video/node_modules/react-native/packager/react-packager/src/Bundler/index.js:695:19)
```

**Comment by mglagola** [comment]
Getting this as well when following https://blog.expo.io/updating-your-project-for-the-exponent-expo-name-change-67aee72c4e2e#.sbrib8bqx (updated `exp` and `ide` too)

**Comment by brentvatne** [comment]
Hello! What versions of XDE and exp do you have? Can you share your package.json?

**Comment by mglagola** [comment]
```js
{
  // ...
  "dependencies": {
    "@exponent/ex-navigation": "~2.7.0",
    "@exponent/vector-icons": "~4.0.0",
    "bluebird": "^3.5.0",
    "lodash": "^4.17.4",
    "query-string": "^4.3.2",
    "react": "~15.4.0",
    "react-native": "https://github.com/exponent/react-native/archive/sdk-14.0.0.tar.gz",
    "react-redux": "^5.0.3",
    "redux": "^3.6.0",
    "redux-logger": "^2.8.1",
    "redux-persist": "^4.4.2",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "babel-eslint": "^7.1.1",
    "eslint": "^3.16.0",
    "eslint-config-standard": "^6.2.1",
    "eslint-config-standard-react": "^4.2.0",
    "eslint-plugin-babel": "^4.0.1",
    "eslint-plugin-jsx-a11y": "^4.0.0",
    "eslint-plugin-promise": "^3.4.2",
    "eslint-plugin-react": "^6.10.0",
    "eslint-plugin-standard": "^2.0.1",
    "exp": "^35.2.0",
    "expo": "^14.0.2",
    "flow-bin": "^0.39.0",
    "jest-exponent": "~0.2.0"
  }
}
```

**Comment by brentvatne** [comment]
you don't have the `exponent` package installed 🤔

**Comment by brentvatne** [comment]
oooh I see, you put expo under devDependencies. that should be under `dependencies`

**Comment by mglagola** [comment]
@brentvatne 🥇 

That worked 😬 , thanks

**Comment by brentvatne** [comment]
sweet! :) @iraycd - maybe the same for you?

**Comment by iraycd** [comment]
<img width="916" alt="screen shot 2017-03-10 at 3 46 59 pm" src="https://cloud.githubusercontent.com/assets/1450984/23791467/17a17cba-05a9-11e7-8f5d-73fef8f108a8.png">
This has been the download speed since a day.

**Comment by iraycd** [comment]
@brentvatne Installed the new XDE. It's solved.

**Comment by vyshkant** [comment]
> oooh  I see, you put expo under devDependencies. that should be under dependencies

@brentvatne  Could you please explain why? I'm using expo while I'm developing "MyPackage", is it nessecary to run "MyPackage" on prod environment?
